// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-west-1:e754315a-119e-4322-8b7b-f2bb35bc974f',
    'aws_cognito_region': 'eu-west-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'andersenapp-hosting-mobilehub-696187195',
    'aws_content_delivery_bucket_region': 'eu-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd13n15hzbnsud6.cloudfront.net',
    'aws_mobile_analytics_app_id': '16b1065a797147f888788cdfa5537970',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '8c5bd8fe-2f32-4e67-b0f3-519defd56a19',
    'aws_project_name': 'AndersenApp',
    'aws_project_region': 'eu-west-1',
    'aws_resource_name_prefix': 'andersenapp-mobilehub-696187195',
}

export default awsmobile;
